### PR TITLE
Use steam launch arguments when clearing steam cache 

### PR DESCRIPTION
**Pull request by LaserFlash**
## Clear Steam Cache uses steam launch args

Previously using the Clear Steam Cache option would not relaunch steam with the specified Steam Launch Arguments. 2dea914 fixes this.

e.g will launch `steam -dev` rather than just `steam` if `-dev` is set as a launch argument

### CODE REVIEW

**Comment by PhantomGamers** [comment]
First off, thanks so much for your PR. I highly appreciate it!

The '{' being included was intentional, as to prevent Steam from utilizing any of the code below so that custom css elements will always override original ones without requiring an !important tag, but we can append a closing tag to the end of the file to prevent the error. I'll have to look into an alternative to it rejecting steamloopback.host

Thanks for bringing that to my attention, as I actually didn't even think to check big picture mode and apparently no one else did either haha

As for the second fix, that was a great find and I'd have no problem merging that.

**Comment by LaserFlash** [comment]
No problem.

Matching with a closing tag at the end of the file results in the same issue in big picture. It wont apply any of the css. Big Picture seems very fussy

**Comment by LaserFlash** [comment]
I updated the pull request to only include the launch arguments changes

**Review by PhantomGamers — APPROVED** [review]

**Comment by PhantomGamers** [comment]
I merged it, also as for the { adding in a closing } at the end wouldn't actually help, because the issue is purely because of the steamloopback problem.

I don't think the issue is that steamloopback doesn't work with big picture, but that the directory that steamloopback points to seems to vary depending on which part of the client is accessing it, so we have to figure out where it points to for big picture and put a hardlink to friends.custom.css an friends.original.css in there hmm

EDIT: I should say, it's entirely possible that it just doesn't work in BPM, but I recall when experimenting with something else (I don't remember what exactly) that it did seem to point to a different folder when accessed from another part of the client (perhaps it was the new library leak)

But looking in dev mode it seems like BPM doesn't access steamloopback at all by default so it might just not be configured for that.

**Pull request merged**
